### ISSUE TITLE
The error occured when I run the project 

### ISSUE THREAD

**Issue by BigRayLee** [tigerk0430/voxelnet_ros#4]
I transfer the kitti dataset to rosbag ,and rosbag publish the point cloud data ,but when I run,the error occured 
``[ERROR] [1540544896.524245]: bad callback: <function velo_callback at 0x7fd4afb1ee18>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "voxelnet_ros.py", line 146, in velo_callback
    z=np_p[:, 2],
IndexError: index 2 is out of bounds for axis 1 with size 2
``
What should I do ?

**Comment by maxwellfrom** [comment]
Have you succeed in running this project by now ? @BigRayLee

**Comment by BigRayLee** [comment]
> Have you succeed in running this project by now ? @BigRayLee

Yes, you just need to erase the "ring" field.

**Comment by maxwellfrom** [comment]
Is it suitable for 16-beam  lidar's data?

**Comment by BigRayLee** [comment]
> Is it suitable for 16-beam lidar's data?

I can input the 16-beam lidar's data, but my rosbag does not include the car point cloud, so the results of detction is not really good. I think if you have the 16-beam lidar's dataset ,you can try.

**Comment by maxwellfrom** [comment]
ok, thanks!

**Comment by BigRayLee** [comment]
> ok, thanks!


> ok, thanks!

**Comment by BigRayLee** [comment]
> ok, thanks!

You're welcome!

**Comment by maxwellfrom** [comment]
> > Have you succeed in running this project by now ? @BigRayLee
> 
> Yes, you just need to erase the "ring" field.


Sorry, I didn't find the "ring" field, what is that?

**Comment by BigRayLee** [comment]
> > > Have you succeed in running this project by now ? @BigRayLee
> > 
> > 
> > Yes, you just need to erase the "ring" field.
> 
> Sorry, I didn't find the "ring" field, what is that?

I just modified the code about ring field  in the voxelnet_ros.py. You need find the source code based on your errors.

**Comment by maxwellfrom** [comment]
I found that "ring", could I add your wechat number? I will sent my wechat number to your mail box, thanks a lot!

**Comment by maxwellfrom** [comment]
> > > > Have you succeed in running this project by now ? @BigRayLee
> > > 
> > > 
> > > Yes, you just need to erase the "ring" field.
> > 
> > 
> > Sorry, I didn't find the "ring" field, what is that?
> 
> I just modified the code about ring field in the voxelnet_ros.py. You need find the source code based on your errors.

I found that "ring", could I add your wechat number? This is my wechat number:15005516063. Thanks!
